apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-pack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dominikmatras/production-pack-k8s.git
    targetRevision: main
    path: charts/production-pack
    helm:
      valueFiles:
        - ../../apps/production-pack/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production-pack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
