imagePullSecrets: []

gateway:
  enabled: true
  host: api.production-pack.dm-tech.pl
  image:
    repository: ghcr.io/dominikmatras-tech/api-gateway
    tag: dev
  containerPort: 8080

services:
  user-service:
    enabled: true
    image:
      repository: ghcr.io/dominikmatras-tech/user-service
      tag: dev
    containerPort: 8081
    env:
      PORT: '8081'
      NODE_ENV: 'production'
    prismaMigrate: false
    dbSecretKey: DATABASE_URL_USER

  order-service:
    enabled: true
    image:
      repository: ghcr.io/dominikmatras-tech/order-service
      tag: dev
    containerPort: 8082
    env:
      PORT: '8082'
      NODE_ENV: 'production'
    prismaMigrate: true
    dbSecretKey: DATABASE_URL_ORDER

  production-service:
    enabled: true
    image:
      repository: ghcr.io/dominikmatras-tech/production-service
      tag: dev
    containerPort: 8083
    env:
      PORT: '8083'
      NODE_ENV: 'production'
    dbSecretKey: DATABASE_URL_ORDER

  report-service:
    enabled: true
    image:
      repository: ghcr.io/dominikmatras-tech/report-service
      tag: dev
    containerPort: 8084
    env:
      PORT: '8084'
      NODE_ENV: 'production'
    prismaMigrate: true
    dbSecretKey: DATABASE_URL_REPORT

secrets:
  jwtSecret: 'productionpack'
