{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
data:
  config.js: |
    window.__APP_CONFIG__ = {
      API_BASE_URL: "{{ .Values.frontend.config.apiBaseUrl }}"
    };
{{- end }}