{{- if .Values.gateway.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ "{{ .Values.gateway.host }}" ]
      secretName: {{ .Release.Name }}-gateway-tls
  rules:
    - host: "{{ .Values.gateway.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway
                port:
                  number: 80
{{- end }}
