apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "pp.fullname" . }}-secrets'
type: Opaque
stringData:
  JWT_SECRET: '{{ .Values.secrets.jwtSecret }}'
  DATABASE_URL_USER: '{{ .Values.secrets.databaseUser }}'
  DATABASE_URL_ORDER: '{{ .Values.secrets.databaseOrder }}'
  DATABASE_URL_REPORT: '{{ .Values.secrets.databaseReport }}'
