apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  DATABASE_URL_USER: {{ .Values.secrets.databaseUrlUser | quote }}
  DATABASE_URL_ORDER: {{ .Values.secrets.databaseUrlOrder | quote }}
  DATABASE_URL_REPORT: {{ .Values.secrets.databaseUrlReport | quote }}
