{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}-{{ $name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ $svc.containerPort }}
{{- end }}
{{- end }}
